language: cpp
dist: trusty

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1
  
before_install:
#g++ 4.9
#- echo 'Installing G++ 4.9'
#- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#- sudo apt-get update -qq
#- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
#- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
#- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50


    
# SugarConvDsk
- echo 'Generating makefile'
- cd SugarConvDsk
- cmake .
- make all

