language: cpp
dist: trusty

#limit to git depth to 1 because don't use any git command in this script
git:
  depth: 1
  
addons:
    apt:
      update: true
      
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
    
# SugarConvDsk
- echo 'Generating makefile'
- cd SugarConvDsk
- cmake .
- make all

