version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - appveyor_build_linux
  

image:
- Visual Studio 2017
- Ubuntu

configuration:
- Release   
#- Debug

platform:
#- x86
- x64

install:
- git submodule init 
- git submodule update
- sh: |- 
    echo 'Installing G++ 7'
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update -qq
    if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-7; fi
    if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 50

  
before_build:
- cmd: |-
    if %platform%==x64 set CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
    else set CMAKE_GENERATOR="Visual Studio 15 2017"
    
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR_SUFFIX%
- sh: |-
    mkdir build
    cd build
    cmake --version
    cmake .. 

    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
    cmake --build . --config %configuration% --target INSTALL
- sh: |-
    make all

#after_build:
#- cmd :|
#     7z a SugarConvDsk.zip %APPVEYOR_BUILD_FOLDER%\build\SugarConvDsk\%configuration%\SugarConvDsk.exe
    

test_script:
- cmd:  |-
    cd c:\projects\SugarConvDsk\build\Tests
    cd %configuration%
    Tests.exe
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - SugarConvDsk/
    - CPCCoreEMu/

artifacts:
    - path: '**\SugarConvDsk.exe'
      name: SugarConvDsk

