version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - test_appveyor
clone_folder: c:\projects\cmake-init
image:
- Visual Studio 2017
configuration:
- Release   
- Debug
platform:
- Win32

install:
- cmd: git submodule init 
- cmd: git submodule update
  
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017"
    
build_script:
- cmake --build . --config %configuration%
- cmake --build . --config %configuration% --target INSTALL

test_script:
- cmd:  |-
    echo "********** TRACES *******"
    dir /s c:\projects\cmake-init\build\
    cd c:\projects\cmake-init\build\Tests
    cd %configuration%
    Tests.exe
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - SugarConvDsk/
    - CPCCoreEMu/

deploy:
    release: SugarConvDsk-v$(APPVEYOR_REPO_TAG_NAME)
    description: 'SugarConvDsk tool for converting and listing Amstrad CPC disk dumps'
    provider : GitHub
    artifacts: c:\projects\cmake-init\build\SugarConvDsk\Release\SugarConvDsk.exe
    auth_token:
        secure: BnoqaLTSDVNx6oPt3nKlP69GTVZpfVUDPnHSweLsR34ZIeIi4pvUIE+Uz3iebEhz
    on:
        branch : test_appveyor
        appveyor_repo_tag: true