version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - appveyor_build_linux
  

image:
- Visual Studio 2017
- Ubuntu1804

configuration:
- Release   
- Debug

platform:
- x86
- x64

install:
- git submodule init 
- git submodule update
- sh: |- 
    echo 'Update to gcc8'
    sudo update-alternatives --set gcc /usr/bin/gcc-8

  
before_build:
- cmd: |-
    if %platform%==x64 (    set CMAKE_GENERATOR="Visual Studio 15 2017 Win64" ) else (   set CMAKE_GENERATOR="Visual Studio 15 2017")   
    mkdir build
    cd build
    cmake --version
    echo %CMAKE_GENERATOR%
    cmake .. -G %CMAKE_GENERATOR%
- sh: |-
    mkdir build
    cd build
    cmake --version
    cmake .. 

    
build_script:
- cmd : |- 
    cmake --build . --config %configuration%
    cmake --build . --config %configuration% --target INSTALL
- sh: |-
    make all

after_build:
- cmd : |- 
    set artifact_name=SugarConvDsk_%platform%.zip
    7z a %artifact_name% %APPVEYOR_BUILD_FOLDER%\build\SugarConvDsk\%configuration%\SugarConvDsk.exe
    echo %artifact_name%
    appveyor PushArtifact %artifact_name%
- sh:  |-
    artifact_name=$APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk_$PLATFORM.gz
    gzip $APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk
    mv $APPVEYOR_BUILD_FOLDER/build/SugarConvDsk/$configuration/SugarConvDsk.gz $artifact_name
    echo $artifact_name
    appveyor PushArtifact $artifact_name

test_script:
- cmd:  |-
    cd c:\projects\SugarConvDsk\build\Tests
    cd %configuration%
    Tests.exe
  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - SugarConvDsk/
    - CPCCoreEMu/
    - Tests/

