version: '{build}'

environment:
  ZLIB_VERSION: 1.2.8.4
  
branches:
  only:
  - master
  - appveyor_setup
clone_folder: c:\projects\cmake-init
image:
- Visual Studio 2017
configuration:
- Release   
- Debug
platform:
- Win32

install:

  
before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G "Visual Studio 15 2017"
    
build:
  project: c:\projects\cmake-init\build\SugarConvDsk.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - SugarConvDsk/
    - CPCCoreEMu/
